Reports
wbtaro/books_app pull request #12
Opened 2020-04-02 05:59 UTC by wbtaro

Add  daily report and comment functions

2020-04-02 09:30 UTC, komagata commented on app/controllers/application_controller.rb
> +    def set_comments_and_new_comment(commentable_resource)
長くて複雑なのでシンプルになるようにメソッドを分けてみてください〜

2020-04-02 09:30 UTC, komagata commented on app/controllers/books_controller.rb
> +      redirect_to @book, notice: I18n.t("results.common.create", resource: I18n.t("activerecord.models.book.one"))
```suggestion
      redirect_to @book, notice: t("results.common.create", resource: I18n.t("activerecord.models.book.one"))
```

2020-04-02 09:30 UTC, komagata commented on app/views/books/show.html.erb
> +<%= render "shared/comments" %>
最終行に改行が内容です。

2020-04-02 09:30 UTC, komagata commented on app/views/reports/show.html.erb
> +  <strong><%= t("activerecord.attributes.report.contributor") %>:</strong>
こういうところは`モデル名.human_attribute_name`を使うといいです〜

2020-04-02 09:30 UTC, komagata commented on app/views/shared/_comments.html.erb
> +  <p>-------------------------------</p>
この行はなんでしょう？

2020-04-02 13:03 UTC, wbtaro commented on app/views/reports/show.html.erb
> +  <strong><%= t("activerecord.attributes.report.contributor") %>:</strong>
他のところも含め、できる限り`モデル名.human_attribute_name`と、`モデル名.model_name.human`を使用するよう、修正しました！

2020-04-02 13:04 UTC, wbtaro commented on app/views/books/show.html.erb
> +<%= render "shared/comments" %>
修正いたしました！

2020-04-02 13:18 UTC, wbtaro commented on app/controllers/application_controller.rb
> +    def set_comments_and_new_comment(commentable_resource)
メソッドを分割しました。
分割後は下記のリンクのようになっております。

`set_posted_comments_ans_commenters`について、①`@posted_comments`を取得する部分と、②`@commenters`を取得する部分を分けると、①→②の順に呼び出さなければならなくなり、若干使いづらくなるかと思い、ひとつのメソッドにまとめています。
（まとめた状態で中身が6行）
やはり分割した方が良ければ、ご指摘いただければと思います。

https://github.com/wbtaro/books_app/blob/reports/app/controllers/application_controller.rb#L43-L54

2020-04-02 13:20 UTC, wbtaro commented on app/views/shared/_comments.html.erb
> +  <p>-------------------------------</p>
コメントが複数ある場合、コメントとコメントの間がわかりづらいので、区切りのために入れています。

2020-04-03 02:54 UTC, komagata commented on app/views/shared/_comments.html.erb
> +  <p>-------------------------------</p>
HTMLのカリキュラムで出てきますが、飾り文字でデザイン要素を作るのは、文章の内容とデザインの分離ができないのでやめた方がいい感じです〜

2020-04-03 03:00 UTC, komagata requested changes

2020-04-06 11:40 UTC, wbtaro commented on app/views/shared/_comments.html.erb
> +  <p>-------------------------------</p>
ご指摘ありがとうございます！
手抜きして申し訳ございません！修正しました！

2020-04-06 11:41 UTC, wbtaro commented on app/controllers/application_controller.rb
> +    def set_posted_comments_and_commenters(commentable_resource)
メソッドを分割しました！

2020-04-06 11:42 UTC, wbtaro commented on app/views/reportlists/show.html.erb
> +<%= render partial: "shared/report_list", locals: { show_user: false } %>
アドバイスありがとうございます。
エディタに設定を追加し、該当箇所を修正いたしました。

2020-04-08 04:34 UTC, komagata requested changes

2020-04-08 04:34 UTC, komagata commented on app/controllers/application_controller.rb
> +      temp_commenters = User.includes(:comments).where(comments: { commentable_id: commentable_resource.id })
SQLのJOINを使って一回のDBアクセスで取得できそうです〜
DBアクセスは重い処理なのでなるべく1度で取ってくるように仕事でも注意されるはずです。

2020-04-08 04:34 UTC, komagata commented on app/controllers/comments_controller.rb
> +      redirect_to commented_resource, notice: I18n.t("results.common.create", resource: I18n.t("activerecord.models.comment.one"))
```suggestion
      redirect_to commented_resource, notice: t("results.common.create", resource: t("activerecord.models.comment.one"))
```

2020-04-08 07:30 UTC, wbtaro commented on app/controllers/application_controller.rb
> +      temp_commenters = User.includes(:comments).where(comments: { commentable_id: commentable_resource.id })
`includes`したテーブルの列に対して`where`で条件指定をした場合は、`JOIN`が使用されるため、当該箇所についてはSQL一本でデータを取得できていると考えているのですが、認識が誤っておりますでしょうか？
（コンソール上では2本SQLが発行されていますが、そのうち一本は直前に呼び出した`set_posted_comments`に対応するものなので、当該箇所については1本だと考えております）

2020-04-08 16:41 UTC, komagata commented on app/controllers/application_controller.rb
> +      temp_commenters = User.includes(:comments).
このメソッドの中の処理が全てeachを使わず一個のSQLでできるかもという意味です〜

2020-04-08 16:41 UTC, komagata commented on app/controllers/application_controller.rb
> +      temp_commenters = User.includes(:comments).
temp_xxxという変数ができるのはメソッドを分けるか、一つの処理でできるというサインになると思います〜（そういう変数はなくて良いはず）

2020-04-09 01:15 UTC, wbtaro commented on app/controllers/application_controller.rb
> +      temp_commenters = User.includes(:comments).
補足いただきありがとうございます！ご指摘の意図を勘違いしておりました。

こちら、ハッシュに入れる処理が入るので、どうしてもSQLのみでの実装は難しく、each２つは必要になってしまいます。

なので、メソッドを分ける方向で修正しました。
`commenter_list`というメソッドが`temp_commenters`に相当する分を切り出したメソッドになります！

2020-04-09 10:44 UTC, komagata commented on app/controllers/application_controller.rb
> +    def set_posted_comments(commentable_resource)
comment関連のcontrollerにしか必要でないので、application_controllerにメソッドを置くのは適切ではないと思います。

それ用のcontrollerを作って継承している方が多いです。

2020-04-09 13:28 UTC, wbtaro commented on app/controllers/application_controller.rb
> +    def set_posted_comments(commentable_resource)
アドバイスありがとうございます！継承を利用するのですね！

新しく`CommnetableResourceController`を作成し、そちらにメソッドを移管、これらのメソッドを使用するコントローラは新しく作成したコントローラを継承するよう修正しました。  
  
また、`DisplayedWithFollowsController`も同様の理由で新規作成しました。  
フォローする、しないを表示する画面に使用するコントローラはこれを継承するようにしています。

2020-04-10 16:56 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-04-12 11:25 UTC, merged