Tests
wbtaro/books_app pull request #13
Opened 2020-04-13 00:54 UTC by wbtaro

Add tests to this application

2020-04-13 13:39 UTC, komagata requested changes
PRのタイトルがTestsだと仕事のプロジェクトだとわからないのでもう少しわかりやすいタイトルを考えてみてください〜

2020-04-13 13:39 UTC, komagata commented on test/system/account_test.rb
> +    fill_in "user_email", with: "date@example.com"
formはなるべくwithinでどのformか限定するのがいいです〜

2020-04-13 13:39 UTC, komagata commented on test/system/followers_test.rb
> +  include Devise::Test::IntegrationHelpers
ApplicationSystemTestCaseにincludeしちゃっていいかもです。

2020-04-14 02:25 UTC, wbtaro commented
ご指摘ありがとうございます！内容を修正し、ブランチ名を変更し、新しくPRを作成しました！
https://github.com/wbtaro/books_app/pull/14

2020-04-14 02:26 UTC, wbtaro commented on test/system/followers_test.rb
> +  include Devise::Test::IntegrationHelpers
修正いたしました。
新しくブランチ名を変えてPRを再作成しましたので、ご確認をお願いいたします。
#14

2020-04-14 02:26 UTC, wbtaro commented on test/system/account_test.rb
> +    fill_in "user_email", with: "date@example.com"
修正いたしました。
新しくブランチ名を変えてPRを再作成しましたので、ご確認をお願いいたします。
#14

2020-04-15 12:34 UTC, closed without merging