Install Active Storage
wbtaro/books_app pull request #9
Opened 2020-03-25 10:56 UTC by wbtaro

Install Active Storage

2020-03-26 04:47 UTC, komagata requested changes
x) avator
o) avatar

だと思います〜

2020-03-26 05:16 UTC, wbtaro commented
スペルを修正しました！

2020-03-26 10:47 UTC, komagata requested changes

2020-03-26 10:47 UTC, komagata commented on config/locales/devise_en.yml
> +        avator: Avatar
```suggestion
        avatar: Avatar
```

2020-03-26 10:47 UTC, komagata commented on config/locales/devise_ja.yml
> +        avator: アイコン画像
```suggestion
        avatar: アイコン画像
```

2020-03-26 23:47 UTC, wbtaro commented on config/locales/devise_ja.yml
> +        avator: アイコン画像
たびたびすみません。
今度こそ修正しました。

2020-03-27 03:35 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-03-27 05:01 UTC, merged